[2025-08-16T06:26:38.802+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:26:38.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:26:38.808+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:26:38.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:26:38.830+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:26:38.824+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:26:38.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:26:38.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.072 seconds
[2025-08-16T06:27:09.140+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:09.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:27:09.144+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:27:09.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:09.158+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:27:09.155+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:27:09.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:09.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.045 seconds
[2025-08-16T06:27:39.488+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:39.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:27:39.491+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:27:39.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:39.503+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:27:39.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:27:39.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:27:39.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.041 seconds
[2025-08-16T06:28:09.951+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:09.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:28:09.953+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:28:09.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:09.967+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:28:09.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:28:09.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:09.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.046 seconds
[2025-08-16T06:28:40.300+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:40.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:28:40.303+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:28:40.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:40.315+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:28:40.312+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:28:40.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:28:40.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.041 seconds
[2025-08-16T06:29:10.673+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:10.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:29:10.676+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:29:10.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:10.690+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:29:10.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:29:10.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:10.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.046 seconds
[2025-08-16T06:29:40.966+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:40.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:29:40.968+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:29:40.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:40.980+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:29:40.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:29:40.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:29:40.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.039 seconds
[2025-08-16T06:30:11.333+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:11.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:30:11.336+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:30:11.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:11.355+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:30:11.351+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:30:11.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:11.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.048 seconds
[2025-08-16T06:30:41.678+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:41.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sales_forecasting_dag.py for tasks to queue
[2025-08-16T06:30:41.681+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:30:41.681+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:41.694+0000] {logging_mixin.py:188} INFO - [2025-08-16T06:30:41.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/sales_forecasting_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sales_forecasting_dag.py", line 5, in <module>
    from scripts.train_model import train_sales_model
ModuleNotFoundError: No module named 'scripts.train_model'
[2025-08-16T06:30:41.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sales_forecasting_dag.py
[2025-08-16T06:30:41.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sales_forecasting_dag.py took 0.040 seconds
